import path from 'node:path';
import { readJsonl, writeJson, writeText } from './fs-utils.mjs';
import { classifyEvents, policySuggestions, summarizeRisks, toYaml } from './risk.mjs';
import { redactEvents } from './redaction.mjs';
import { sessionFile } from './session.mjs';

export function renderSession(session) {
  const rawEvents = readJsonl(sessionFile(session.dir, 'session.jsonl'));
  const classified = classifyEvents(rawEvents, session.meta);
  const { redacted, stats } = redactEvents(classified);
  const counts = summarizeRisks(redacted);
  const policies = policySuggestions(redacted);
  const reviewItems = trustChecklist(redacted);

  writeText(sessionFile(session.dir, 'session.redacted.jsonl'), redacted.map((event) => JSON.stringify(event)).join('\n') + '\n');
  writeJson(sessionFile(session.dir, 'redactions.json'), { generated_at: new Date().toISOString(), redactions: stats });
  writeText(sessionFile(session.dir, 'policy-suggestions.yaml'), toYaml({ rules: policies }) + '\n');
  writeText(sessionFile(session.dir, 'risk.md'), renderRiskMarkdown(session.meta, redacted, counts, reviewItems));
  writeText(sessionFile(session.dir, 'executive-summary.md'), renderExecutiveSummary(session.meta, redacted, counts, stats, policies, reviewItems));
  writeText(sessionFile(session.dir, 'pr-review.md'), renderPrReviewMarkdown(session.meta, redacted, counts, reviewItems));
  writeText(sessionFile(session.dir, 'replay.html'), renderHtml(session.meta, redacted, counts, stats, policies, reviewItems));

  return { events: redacted, counts, stats, policies, reviewItems };
}

function renderExecutiveSummary(meta, events, counts, redactions, policies, reviewItems) {
  const highRisk = events.filter((event) => ['critical', 'high'].includes(event.risk));
  const writes = events.filter((event) => event.event_type === 'write');
  const executes = events.filter((event) => event.event_type === 'execute');
  const toolCalls = events.filter((event) => event.event_type === 'tool_call');
  const scopeDrift = events.filter((event) => (event.risk_tags || []).includes('scope_drift'));
  const preexistingIgnored = sumMeta(events, 'preexisting_ignored_count');
  const recommendation = counts.critical > 0
    ? 'Do not trust blindly. Human review required before merge, deploy, send, or handoff.'
    : counts.high > 0
      ? 'Review high-risk items before trusting this run.'
      : 'Low immediate risk detected by V0 rules, but capture is partial.';

  return `# Agent Ledger Executive Summary

Session: ${meta.name}

Goal: ${meta.goal || 'n/a'}

Scope: ${meta.scope || 'n/a'}

## Verdict

${recommendation}

## What Happened

- Events captured: ${events.length}
- File/write events: ${writes.length}
- Command executions: ${executes.length}
- Tool calls: ${toolCalls.length}
- Scope drift events: ${scopeDrift.length}
- Pre-existing dirty paths ignored: ${preexistingIgnored}
- Redaction patterns triggered: ${redactions.length}

## Risk Snapshot

- Critical: ${counts.critical || 0}
- High: ${counts.high || 0}
- Medium: ${counts.medium || 0}
- Low: ${counts.low || 0}

## Read This Before Trusting The Run

${reviewItems.map((item) => `- ${item}`).join('\n') || '- No blocking review items generated by V0 rules.'}

## Top Risk Events

${highRisk.slice(0, 8).map((event) => `- **${event.risk.toUpperCase()}** ${event.event_type} \`${event.target || 'n/a'}\`: ${event.summary}`).join('\n') || '- No critical/high events detected.'}

## Suggested Policy Updates

${policies.slice(0, 8).map((item) => `- \`${JSON.stringify(item)}\``).join('\n') || '- No policy suggestions generated.'}

## Supervisor-Agent Input

Use this section as input for a higher-level review agent:

> Review this run as an accountability supervisor. Decide whether the human can trust it, what must be checked manually, what policy should change, and whether the original goal was satisfied. Do not assume complete capture: missing evidence is unknown, not safe.

## V0 Limit

This is a partial local ledger. It is useful for review and coordination, but it is not yet a complete agent observability or security system.
`;
}

function renderPrReviewMarkdown(meta, events, counts, reviewItems) {
  const status = prStatus(counts);
  const highRisk = events.filter((event) => ['critical', 'high'].includes(event.risk));
  const writes = events.filter((event) => event.event_type === 'write');
  const executes = events.filter((event) => event.event_type === 'execute');
  const verificationEvents = events.filter((event) => {
    const text = `${event.summary || ''} ${event.target || ''}`.toLowerCase();
    return /\b(test|check|lint|verify|validation|smoke)\b/.test(text);
  });

  return `# Agent Ledger PR Review Record

<!-- agent-ledger:pr-review:v0.1 -->

Status: ${status.kind}

${status.badge} **${status.label}** - ${status.summary}

## Run Context

- Session: \`${meta.name}\`
- Goal: ${meta.goal || 'n/a'}
- Scope: ${meta.scope || 'n/a'}
- Project: \`${meta.project_path || 'n/a'}\`

## Risk Snapshot

- Critical: ${counts.critical || 0}
- High: ${counts.high || 0}
- Medium: ${counts.medium || 0}
- Low: ${counts.low || 0}

## Reviewer Actions

${reviewItems.map((item) => `- ${item}`).join('\n') || '- No blocking review items generated by V0 rules.'}

## Evidence-Based Findings

${renderPrFindings(highRisk)}

## Files And Commands Summary

- Files/write events: ${writes.length}
- Command executions: ${executes.length}
- Verification-like events observed: ${verificationEvents.length}

${writes.slice(0, 12).map((event) => `- \`${event.target || 'n/a'}\`: ${event.summary}`).join('\n') || '- No write events captured.'}
${writes.length > 12 ? `\n- ${writes.length - 12} additional write event(s) omitted from this PR summary. Open \`files-touched.csv\` for the full list.` : ''}

## Local Artifacts

- Executive summary: \`executive-summary.md\`
- Risk debrief: \`risk.md\`
- Replay: \`replay.html\`
- Files touched: \`files-touched.csv\`
- Pre-existing dirty baseline: \`preexisting-dirty.csv\`

## V0 Limit

This is a local-first review record for AI-generated changes. Missing transcript, hooks, tests or CI evidence is unknown, not safe.
`;
}

function renderPrFindings(events) {
  if (!events.length) {
    return '- No critical/high findings detected. Still review touched files, verification evidence and baseline limits before merge.';
  }

  return events.slice(0, 8).map((event, index) => {
    const reasons = event.risk_reasons?.length ? event.risk_reasons.join('; ') : 'Risk rule matched.';
    return `### AL-${String(index + 1).padStart(3, '0')} - ${event.risk.toUpperCase()} ${event.event_type}

- Evidence: \`${event.target || 'n/a'}\`
- Why it matters: ${reasons}
- Reviewer action: inspect this change before merge and require a fix or explicit acceptance if the risk is real.
- Summary: ${event.summary}`;
  }).join('\n\n');
}

function prStatus(counts) {
  if ((counts.critical || 0) > 0) {
    return {
      kind: 'BLOCK',
      badge: '[BLOCK]',
      label: 'Human review required before merge',
      summary: 'Critical Agent Ledger finding(s) were detected.'
    };
  }
  if ((counts.high || 0) > 0) {
    return {
      kind: 'WARN',
      badge: '[WARN]',
      label: 'Review high-risk items before merge',
      summary: 'High-risk Agent Ledger finding(s) were detected.'
    };
  }
  return {
    kind: 'PASS',
    badge: '[PASS]',
    label: 'No critical/high findings detected',
    summary: 'V0 rules did not find critical or high-risk events, but the run still needs normal code review.'
  };
}

function renderRiskMarkdown(meta, events, counts, reviewItems) {
  const high = events.filter((event) => ['critical', 'high'].includes(event.risk));
  const preexistingIgnored = sumMeta(events, 'preexisting_ignored_count');
  return `# Agent Ledger Risk Debrief

Session: ${meta.name}

Goal: ${meta.goal || 'n/a'}

## Risk Counts

- Critical: ${counts.critical || 0}
- High: ${counts.high || 0}
- Medium: ${counts.medium || 0}
- Low: ${counts.low || 0}

## What To Review Before Trusting This Run

${reviewItems.map((item) => `- ${item}`).join('\n') || '- No blocking review items generated.'}

## Baseline Context

- Pre-existing dirty paths ignored: ${preexistingIgnored}

## High-Risk Events

${high.map((event) => `- **${event.risk.toUpperCase()}** ${event.event_type} \`${event.target || 'n/a'}\`: ${event.summary}`).join('\n') || '- None.'}

## Accountability Notes

- This V0 is a local ledger, not a complete capture system.
- Treat missing hooks/transcripts as unknown, not safe.
- Use this debrief to update future allow/ask/block/warn policy.
`;
}

function renderHtml(meta, events, counts, redactions, policies, reviewItems) {
  const rows = events.map((event) => `
    <tr class="risk-${event.risk}">
      <td>${escapeHtml(event.ts)}</td>
      <td><span class="pill">${escapeHtml(event.actor)}</span></td>
      <td>${escapeHtml(event.source)}</td>
      <td>${escapeHtml(event.event_type)}</td>
      <td><strong>${escapeHtml(event.risk)}</strong><br><small>${escapeHtml((event.risk_tags || []).join(', '))}</small></td>
      <td><code>${escapeHtml(event.target || '')}</code></td>
      <td>${escapeHtml(event.summary)}${event.risk_reasons?.length ? `<br><small>${escapeHtml(event.risk_reasons.join(' | '))}</small>` : ''}</td>
    </tr>
  `).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Agent Ledger - ${escapeHtml(meta.name)}</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f7f8fa;
      --panel: #ffffff;
      --ink: #1b1f24;
      --muted: #657080;
      --line: #d8dee8;
      --low: #edf7ee;
      --medium: #fff7da;
      --high: #fff0e8;
      --critical: #ffe8e8;
      --accent: #184c78;
    }
    * { box-sizing: border-box; }
    body { margin: 0; background: var(--bg); color: var(--ink); font: 14px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    main { max-width: 1180px; margin: 0 auto; padding: 28px; }
    h1, h2 { margin: 0 0 12px; line-height: 1.15; }
    h1 { font-size: 28px; }
    h2 { font-size: 18px; margin-top: 24px; }
    p { margin: 0 0 10px; color: var(--muted); }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; word-break: break-word; }
    .grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; margin: 18px 0; }
    .card { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 14px; }
    .metric { font-size: 24px; font-weight: 700; }
    .label { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0; }
    .pill { display: inline-block; border: 1px solid var(--line); border-radius: 999px; padding: 2px 8px; background: #fff; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; background: var(--panel); border: 1px solid var(--line); border-radius: 8px; overflow: hidden; }
    th, td { border-bottom: 1px solid var(--line); padding: 9px; text-align: left; vertical-align: top; }
    th { background: #eef2f6; font-size: 12px; color: #46515f; }
    tr.risk-low { background: var(--low); }
    tr.risk-medium { background: var(--medium); }
    tr.risk-high { background: var(--high); }
    tr.risk-critical { background: var(--critical); }
    ul { margin-top: 6px; padding-left: 20px; }
    .muted { color: var(--muted); }
    @media (max-width: 820px) {
      main { padding: 16px; }
      .grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      table { font-size: 12px; }
      th, td { padding: 7px; }
    }
  </style>
</head>
<body>
<main>
  <h1>Agent Ledger</h1>
  <p>Local accountability record for an AI agent run.</p>

  <section class="card">
    <h2>Session</h2>
    <p><strong>${escapeHtml(meta.name)}</strong></p>
    <p>Goal: ${escapeHtml(meta.goal || 'n/a')}</p>
    <p>Scope: ${escapeHtml(meta.scope || 'n/a')}</p>
    <p>Project: <code>${escapeHtml(meta.project_path)}</code></p>
  </section>

  <section class="grid">
    ${metric('Critical', counts.critical || 0)}
    ${metric('High', counts.high || 0)}
    ${metric('Medium', counts.medium || 0)}
    ${metric('Low', counts.low || 0)}
  </section>

  <section class="card">
    <h2>What To Review Before Trusting This Run</h2>
    <ul>${reviewItems.map((item) => `<li>${escapeHtml(item)}</li>`).join('\n') || '<li>No blocking review items generated.</li>'}</ul>
  </section>

  <section class="card">
    <h2>Human Brief</h2>
    <p><strong>${escapeHtml(summaryVerdict(counts))}</strong></p>
    <p>${events.length} events captured. ${events.filter((event) => event.event_type === 'write').length} write events, ${events.filter((event) => event.event_type === 'execute').length} commands, ${events.filter((event) => event.event_type === 'tool_call').length} tool calls.</p>
    <p>For a manager-level view, open <code>executive-summary.md</code>.</p>
  </section>

  <section class="card">
    <h2>Redaction Summary</h2>
    <ul>${redactions.map((item) => `<li>${escapeHtml(item.pattern)}: ${item.count} (${escapeHtml(item.severity)})</li>`).join('\n') || '<li>No redactions applied.</li>'}</ul>
  </section>

  <section class="card">
    <h2>Policy Suggestions</h2>
    <ul>${policies.map((item) => `<li><code>${escapeHtml(JSON.stringify(item))}</code></li>`).join('\n') || '<li>No policy suggestions generated.</li>'}</ul>
  </section>

  <h2>Timeline</h2>
  <table>
    <thead>
      <tr>
        <th>Time</th>
        <th>Actor</th>
        <th>Source</th>
        <th>Type</th>
        <th>Risk</th>
        <th>Target</th>
        <th>Summary</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
</main>
</body>
</html>`;
}

function summaryVerdict(counts) {
  if ((counts.critical || 0) > 0) return 'Human review required before trusting this run.';
  if ((counts.high || 0) > 0) return 'Review high-risk items before trusting this run.';
  return 'No critical/high events detected by V0 rules.';
}

function trustChecklist(events) {
  const items = [];
  const critical = events.filter((event) => event.risk === 'critical');
  const high = events.filter((event) => event.risk === 'high');
  const writes = events.filter((event) => event.event_type === 'write');
  const deletes = events.filter((event) => event.event_type === 'delete');
  const unverified = events.filter((event) => (event.risk_tags || []).includes('missing_verification'));
  const secrets = events.filter((event) => (event.risk_tags || []).includes('secret_possible'));
  const scopeDrift = events.filter((event) => (event.risk_tags || []).includes('scope_drift'));
  const preexistingIgnored = sumMeta(events, 'preexisting_ignored_count');

  if (critical.length) items.push(`Review ${critical.length} critical event(s) before trusting this run.`);
  if (high.length) items.push(`Review ${high.length} high-risk event(s), especially sensitive paths and side effects.`);
  if (writes.length) items.push(`Inspect ${writes.length} write event(s) against the stated goal and scope.`);
  if (deletes.length) items.push(`Confirm ${deletes.length} delete event(s) were intended.`);
  if (secrets.length) items.push(`Confirm redaction and secret handling for ${secrets.length} possible secret event(s).`);
  if (scopeDrift.length) items.push(`Review ${scopeDrift.length} event(s) outside the declared scope.`);
  if (preexistingIgnored) items.push(`${preexistingIgnored} pre-existing dirty path(s) were ignored from run risk; inspect preexisting-dirty.csv if repo-wide confidence matters.`);
  if (unverified.length) items.push(`Run missing verification checks before merge/deploy.`);
  if (!events.some((event) => event.source === 'transcript')) items.push('No transcript was ingested; agent reasoning/tool context may be incomplete.');
  if (!events.some((event) => event.source === 'git')) items.push('No git ingest was found; file changes may be incomplete.');
  return [...new Set(items)];
}

function sumMeta(events, key) {
  return events.reduce((sum, event) => sum + Number(event.meta?.[key] || 0), 0);
}

function metric(label, value) {
  return `<div class="card"><div class="metric">${value}</div><div class="label">${escapeHtml(label)}</div></div>`;
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}
